#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config_def = require(__DIR__ . '/config/default/console.php');
$config_env = require(__DIR__ . '/config/' . YII_ENV . '/console.php');

exit((new yii\console\Application(array_replace_recursive($config_def, $config_env)))->run());
